### ISSUE TITLE
UCAB - Game crash 

### ISSUE THREAD

**Issue by Gelegenheitscode** [rettichlp/UnicacityAddon-1.12.2#120]
**Beschreibe den Bug oder Fehler**
Das Spiel crasht beim joinen auf den Minecraft server, da die Fuzzlemann Website mit den HouseBans nicht erreichbar ist.

**Wie kann der Bug oder Fehler reproduziert werden?**
Schritte zum Reproduzieren des Verhaltens:
1. Minecraft starten
2. Uc joinen
3. Dort ist der Fehler

**Erwartetes Verhalten**
Das game crasht nicht

**Screenshots**
/

**Weitere Informationen (bitte ausfüllen):**
Minecraft Version: `1.12.2`
Addon Version: `1.1.1` & `1.2.0-dev`

**Comment by rettichlp** [comment]
Hier erwähnt:
- [Unicacity Forum 1](https://forum.unicacity.de/index.php?thread/96801-unicacity-addon-labymod-addon-by-rettichlp-dimiikou-v1-1-1/&postID=896822#post896822)
- [Unicacity Forum 2](https://forum.unicacity.de/index.php?thread/96801-unicacity-addon-labymod-addon-by-rettichlp-dimiikou-v1-1-1/&postID=896845#post896845)

Fixed with [v1.1.2](https://github.com/rettichlp/UnicacityAddon-1.12.2/releases/tag/v1.1.2)
